# Generated by Django 3.0.7 on 2020-06-17 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_message_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Maktab nomi')),
                ('address', models.CharField(max_length=150, verbose_name='Maktab manzili')),
                ('phone', models.CharField(max_length=150, verbose_name='Telefon raqam')),
                ('contract_num', models.CharField(blank=True, max_length=50, verbose_name='Shartnoma No.')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('contract_finish', models.DateField(verbose_name='Time limit')),
                ('status', models.BooleanField(default=True, verbose_name='Maktab holati')),
            ],
            options={
                'verbose_name': 'Maktab',
                'verbose_name_plural': 'Maktablar',
                'ordering': ['-contract_finish'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20, null=True, verbose_name='Kirish paroli')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.School', verbose_name='Maktab nomi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin & student',
                'verbose_name_plural': 'Admins & students',
            },
        ),
    ]
