# Generated by Django 3.0.7 on 2020-06-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_school_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='type',
            field=models.IntegerField(default=1, verbose_name='TypeUser'),
        ),
    ]
