# Generated by Django 3.0.7 on 2020-06-22 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_userprofile_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Guruh nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('end', models.DateField(verbose_name='Tugash muddati')),
                ('status', models.BooleanField(default=True, verbose_name='Guruh holati')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.School', verbose_name='Maktab nomi')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.UserProfile', verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
                'ordering': ['-end'],
            },
        ),
    ]
