# Generated by Django 3.0.7 on 2020-06-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200622_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='password',
            field=models.CharField(default='123456', max_length=150, verbose_name='Guruh paroli'),
        ),
    ]
