# Generated by Django 3.0.7 on 2020-06-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_group_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='password',
            field=models.CharField(max_length=150, verbose_name='Guruh paroli'),
        ),
    ]
