# Generated by Django 3.0.7 on 2020-06-22 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_userprofile_sinf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sinf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.Group', verbose_name='Guruh nomi'),
        ),
    ]
