# Generated by Django 3.0.7 on 2020-06-23 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Fan nomi')),
                ('begin', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('days', models.ManyToManyField(help_text='Ctrl+mouse left', to='blog.Days', verbose_name='Hafta kunlari')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.School', verbose_name='Maktab nomi')),
                ('sinf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.Groups', verbose_name='Guruh nomi')),
            ],
        ),
    ]
