# Generated by Django 3.0.7 on 2020-06-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200623_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='days',
            field=models.ManyToManyField(help_text='Ctrl+mouse left', to='blog.Days', verbose_name='Hafta kunlari'),
        ),
    ]
