# Generated by Django 3.0.7 on 2020-06-23 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200623_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='days',
        ),
        migrations.AddField(
            model_name='schedule',
            name='days',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.Days', verbose_name='Hafta kunlari'),
        ),
    ]
