# Generated by Django 3.0.7 on 2020-06-23 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200623_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='days',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='blog.Days', verbose_name='Hafta kunlari'),
        ),
    ]
