# Generated by Django 3.0.7 on 2020-06-24 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200623_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Fan', 'verbose_name_plural': 'Fanlar'},
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('status', models.BooleanField(default=True, verbose_name='Dars holati')),
                ('days', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Days', verbose_name='Hafta kuni')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Groups', verbose_name='Guruh')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Schedule', verbose_name='Fan')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.School', verbose_name='Maktab')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.UserProfile', verbose_name='Boshlagan')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
            },
        ),
    ]
