# Generated by Django 3.0.7 on 2020-06-24 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20200624_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Holati')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Groups', verbose_name='Guruh')),
                ('lessons', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Lessons', verbose_name='Dars')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.School', verbose_name='Maktab')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.UserProfile', verbose_name='Talaba')),
            ],
        ),
    ]
