# Generated by Django 3.0.7 on 2020-06-24 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessons',
            old_name='group',
            new_name='sinf',
        ),
    ]
