# Generated by Django 3.0.7 on 2020-06-24 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20200624_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessons',
            old_name='sinf',
            new_name='group',
        ),
    ]
