# Generated by Django 3.0.7 on 2020-06-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20200624_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Sana'),
        ),
    ]
