# Generated by Django 3.0.7 on 2020-06-29 04:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_lessons_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='lessons',
            new_name='lesson',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='group',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='school',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='vaqt'),
            preserve_default=False,
        ),
    ]
