# Generated by Django 3.0.7 on 2020-06-29 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20200629_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TimeField(auto_now_add=True, verbose_name='vaqt')),
                ('context', models.TextField(blank=True, verbose_name='chatmessage')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Lessons', verbose_name='Dars')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.UserProfile', verbose_name='Talaba')),
            ],
        ),
    ]
