# Generated by Django 3.0.7 on 2020-06-29 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='userprofile',
            new_name='sender',
        ),
    ]
